/*
 * generated by Xtext
 */
package php.ware;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityRuntimeModule extends php.ware.AbstractEntityRuntimeModule {

}
